swagger: '2.0'
info:
  title: Synthetic Data Generation Service
  version: 1.0.0
basePath: /v1/synth
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /generate:
    put:
      summary: Generates synthetic data
      consumes:
        - application/json
      produces:
        - application/json
      description: Generates the synthetic data using config json provided
      operationId: generateSyntheticData    # name of generated function
      x-swagger-router-controller: default_controller
      parameters:
        -
          name: configuration
          in: body
          description: Synthetic Data configuration json
          required: true
          schema:
            type: object

      responses:
        200:
          description: OK
        400:
          description: BAD REQUEST
