apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sds-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sds
            port:
              number: 8080
---
